const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';


const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const REFETCH_REQUESTS = "REFETCH_REQUESTS";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_LEAVED = "CHAT_LEAVED";
const CHAT_JOINED = "CHAT_JOINED";
const ONLINE_USERS = "ONLINE_USERS";


export { 
    ALERT, 
    REFETCH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST,
    REFETCH_REQUESTS,
    NEW_MESSAGE,
    START_TYPING,
    STOP_TYPING,
    CHAT_LEAVED,
    CHAT_JOINED,
    ONLINE_USERS,
};


